version: "3"

services:
  blog:
    image: davigsilva/jigsaw-blog
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/app
    working_dir: /app
    command: vendor/bin/jigsaw serve --host 0.0.0.0
